version: 2

project_name: tinycord

builds:
  - id: tinycord
    builder: zig
    binary: tinycord
    dir: apps/desktop
    targets:
      - aarch64-macos
      - x86_64-macos
    flags:
      - -Doptimize=ReleaseSafe

universal_binaries:
  - id: tinycord
    ids:
      - tinycord
    replace: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
