version: 2

project_name: tinycord

env:
  - SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk

builds:
  - builder: zig
    binary: tinycord
    dir: apps/desktop
    targets:
      - aarch64-macos
      - x86_64-macos
      - aarch64-windows-gnu
      - x86_64-windows-gnu
    flags:
      - -Doptimize=ReleaseSafe
      - --sysroot
      - '{{ .Env.SDKROOT }}'

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
